blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/OWNER/syncwingetlink/discussions
    about: For general questions (not bugs or feature requests), please use Discussions.
